# Generated by Django 4.0.4 on 2022-06-09 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import visual_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Автору')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(max_length=150, null=True, verbose_name='Описание')),
                ('cover', models.ImageField(upload_to=visual_image.models.user_directory_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_image.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Почта')),
            ],
        ),
    ]
