# Generated by Django 4.0.4 on 2022-05-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual_image', '0002_remove_image_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.CharField(max_length=50, null=True, verbose_name='Автору'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_image.category', verbose_name='Категориям'),
        ),
    ]
