# Generated by Django 4.0.4 on 2022-05-07 08:32

from django.db import migrations, models
import visual_image.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_image', '0002_remove_image_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, verbose_name=visual_image.models.Image)),
            ],
        ),
    ]
